src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Models/ErrorViewModel.cs
using System;

namespace ViewComponentDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentDemo.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int UnitsInStock { get; set; }
        public bool Discontinued { get; set; }
        public double Cost { get; set; }
        public DateTime LaunchDate { get; set; }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentDemo.Models
{
    public class ProductViewModel
    {
        public int ProductsCount { get; set; }
        public double StockWorth { get; set; }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Models/ProductsData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentDemo.Models
{
    public class ProductsData
    {
        private List<Product> _Products = new List<Product>
        {
            new Product {
                ProductID = 1,
                ProductName = "AMD Ryzen 3990",
                Quantity=100,
                UnitsInStock=50,
                Discontinued = false,
                Cost=3000,
                LaunchDate=new DateTime(2019,10,1)
            },
            new Product {
                ProductID = 2,
                ProductName = "AMD Ryzen 3970",
                Quantity=100,
                UnitsInStock=70,
                Discontinued = false,
                Cost=2500,
                LaunchDate=new DateTime(2019,10,5)
            },
               new Product {
                ProductID = 3,
                ProductName = "AMD Ryzen 3960",
                Quantity=100,
                UnitsInStock=80,
                Discontinued = false,
                Cost=2000,
                LaunchDate=new DateTime(2019,10,15)
            },
                  new Product {
                ProductID = 4,
                ProductName = "AMD Ryzen 3950",
                Quantity=100,
                UnitsInStock=40,
                Discontinued = false,
                Cost=1500,
                LaunchDate=new DateTime(2019,10,25)
            }

        };

        public IEnumerable<Product> Products => _Products;
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Areas/AdminSupport/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentDemo.Areas.AdminSupport.Controllers
{
    [Area("AdminSupport")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Areas/Billing/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentDemo.Areas.Billing.Controllers
{
    [Area("Billing")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ViewComponentDemo.Models;

namespace ViewComponentDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Controllers/MyProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponentDemo.Models;

namespace ViewComponentDemo.Controllers
{
    [ViewComponent(Name ="ProductControllerHybrid")]
    public class MyProductsController : Controller
    {
        private readonly ProductsData pdata;

        public MyProductsController(ProductsData pdata)
        {
            this.pdata = pdata;
        }
        public IActionResult Index()
        {
            return View(pdata.Products);
        }
        public IViewComponentResult Invoke(int Units)
        {

            return new ViewViewComponentResult()
            {
                ViewData = new ViewDataDictionary<ProductViewModel>(
                    ViewData,
                    new ProductViewModel
                    {
                        ProductsCount = pdata.Products.Where(n => n.UnitsInStock >= Units).Count(),
                        StockWorth = pdata.Products.Where(n => n.UnitsInStock >= Units).Sum(c => c.Cost)
                    })
            };
           
        }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Controllers/ProductInTagDemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ViewComponentDemo.Models;

namespace ViewComponentDemo.Controllers
{
    public class ProductInTagDemoController : Controller
    {
        private readonly ProductsData productsData;

        public ProductInTagDemoController(ProductsData productsData)
        {
            this.productsData = productsData;
        }
        public IActionResult Index()
        {
            return View(productsData.Products);
        }
        public IActionResult Details(int id)
        {
            return View(productsData.Products.FirstOrDefault(a => a.ProductID == id));
        }
        [Route("/ProductInTagDemo/ShowAllProducts",Name ="ListOfProducts")]
        public IActionResult ShowAllProducts()
        {
            return View(productsData.Products);
        }
    }
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<h3>
    <a asp-controller="ProductInTagDemo" asp-action="Index">Show All Products</a>
</h3>

<h3><a asp-route="ListOfProducts">List Of Products</a></h3>

<h3>
    <a asp-controller="ProductInTagDemo"
       asp-action="Index"
       asp-fragment="BestSellingProducts">Best Selling Products</a>
</h3>


<h3>
    <a asp-protocol="https"
       asp-controller="Home"
       asp-action="Privacy">Privacy</a>
</h3>


<h3>
    <a asp-protocol="https"
       asp-host="microsoft.com"
       asp-controller="Home"
       asp-action="About">About</a>
</h3>


@*<h3>
        <a asp-area="Billing"
           asp-controller="Home"
           asp-action="Index">Billing Index</a>
    </h3>


    <h3>
        <a asp-area="AdminSupport"
           asp-controller="Home"
           asp-action="Index">AdminSupport Index</a>
    </h3>

    <h6 class="bg-primary text-white m-2 p-2">
        Uncached timestamp: @DateTime.Now.ToLongTimeString()
    </h6>*@

@*<cache enabled="true">
        <h6 class="bg-primary text-white m-2 p-2">
            Cached timestamp: @DateTime.Now.ToLongTimeString()
        </h6>
    </cache>*@

@*<cache expires-after="@TimeSpan.FromSeconds(15)">
        <h6 class="bg-primary text-white m-2 p-2">
            Cached timestamp: @DateTime.Now.ToLongTimeString()
        </h6>
    </cache>*@


@*<cache expires-on="@new DateTime(2020,11,18,19,58,0)">
        <h6 class="bg-primary text-white m-2 p-2">
            Cached timestamp: @DateTime.Now.ToLongTimeString()
        </h6>
    </cache>*@

@*<cache expires-sliding="@TimeSpan.FromSeconds(60)">
        <h6 class="bg-primary text-white m-2 p-2">
            Cached timestamp: @DateTime.Now.ToLongTimeString()
        </h6>
    </cache>*@
<table class="table table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th colspan="2">Employee Details</th>
        </tr>
    </thead>
    <tbody>
        <tr><th>Employee ID</th><td>1</td></tr>
        <tr><th>Employee Name</th><td>Lalit</td></tr>
        <tr><th>Salary</th><td>$5000</td></tr>
    </tbody>
</table>
@section Summary {
    <div class="bg-info text-white m-2 p-2">
        @*@await Component.InvokeAsync("ProductSummary")*@

        @await Component.InvokeAsync("ProductSummary", new { units = 45 })
    </div>


    <div class="bg-info text-white m-2 p-2">
        <vc:product-summary units="45" />
        @*<vc:product-summary  />*@
    </div>
}

src/MvcDemo/MvcDemoVC_V1/ViewComponentDemo/ViewComponentDemo/Views/Shared/Components/ProductControllerHybrid/Default.cshtml
@model ViewComponentDemo.Models.ProductViewModel

@{
    ViewData["Title"] = "Default";
}

<h1>Default</h1>

<div>
    <h4>ProductViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductsCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductsCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockWorth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockWorth)
        </dd>
    </dl>
</div>